# Generated by Django 4.2 on 2026-03-14 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название уровня')),
                ('code', models.CharField(max_length=50, verbose_name='Код уровня')),
                ('zone', models.CharField(max_length=200, verbose_name='Зона доступа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уровень доступа',
                'verbose_name_plural': 'Уровни доступа',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('fired', 'Уволен'), ('blocked', 'Заблокирован')], default='active', max_length=20, verbose_name='Статус')),
                ('photo', models.CharField(blank=True, max_length=200, verbose_name='Ключ фото (MinIO)')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.department', verbose_name='Отдел')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название должности')),
                ('department_name', models.CharField(max_length=200, verbose_name='Название отдела')),
                ('team_name', models.CharField(blank=True, max_length=200, verbose_name='Название команды')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Номер паспорта')),
                ('passport_date', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('passport_issued_by', models.CharField(max_length=300, verbose_name='Кем выдан')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('address', models.TextField(verbose_name='Адрес прописки')),
                ('snils', models.CharField(max_length=20, verbose_name='СНИЛС')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('education_year', models.IntegerField(verbose_name='Год окончания учебного заведения')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
                ('education_name', models.CharField(max_length=200, verbose_name='Название образования')),
                ('diploma_number', models.CharField(max_length=100, verbose_name='Номер диплома')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.administrator', verbose_name='Администратор')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.department', verbose_name='Отдел')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Карточка сотрудника',
                'verbose_name_plural': 'Карточки сотрудников',
            },
        ),
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_hash', models.CharField(blank=True, max_length=500, verbose_name='Hash лица')),
                ('palm_hash', models.CharField(blank=True, max_length=500, verbose_name='Hash ладони')),
                ('face_registered_at', models.DateField(blank=True, null=True, verbose_name='Дата регистрации hash лица')),
                ('palm_registered_at', models.DateField(blank=True, null=True, verbose_name='Дата регистрации hash ладони')),
                ('status', models.BooleanField(default=False, verbose_name='Статус биометрии')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.department', verbose_name='Отдел')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Биометрические данные',
                'verbose_name_plural': 'Биометрические данные',
            },
        ),
        migrations.AddField(
            model_name='administrator',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateField(verbose_name='Дата назначения')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.accesslevel', verbose_name='Уровень доступа')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.department', verbose_name='Отдел')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
            },
        ),
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('access_point', models.CharField(max_length=200, verbose_name='Точка доступа')),
                ('result', models.CharField(choices=[('allowed', 'Разрешён'), ('denied', 'Запрещён')], max_length=20, verbose_name='Результат')),
                ('method', models.CharField(choices=[('password', 'Пароль'), ('biometric', 'Биометрия')], max_length=20, verbose_name='Способ входа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'История проходов',
                'verbose_name_plural': 'История проходов',
                'ordering': ['-datetime'],
            },
        ),
    ]
