# Generated by Django 4.2 on 2026-03-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_position_department_name_position_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessright',
            name='department',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='department',
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeecard',
            name='department',
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.administrator', verbose_name='Администратор'),
        ),
    ]
