# Generated by Django 4.2 on 2026-03-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_accessright_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
