# Generated by Django 4.2 on 2026-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecard',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='diploma_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер диплома'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='education_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название образования'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='education_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год окончания учебного заведения'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=300, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='snils',
            field=models.CharField(blank=True, max_length=20, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специальность'),
        ),
    ]
