# Generated by Django 4.2 on 2026-05-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_accesshistory_camera_source_accesshistory_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdata',
            name='face_hash',
            field=models.TextField(blank=True, verbose_name='Hash лица'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='palm_hash',
            field=models.TextField(blank=True, verbose_name='Hash ладони'),
        ),
    ]
